### ISSUE TITLE
problem about last-modified when press cmd+s

### ISSUE THREAD

**Issue by Louis-udm** [sidmishraw/topper#3]
there is a problem:
When we press cmd+s, Topper should modify the "last-modified" before save the file. ^_*

**Comment by Louis-udm** [comment]
and, when topper check the "last-modified" for modify, it should check only the head of the file, if not there will a problem like:
```
    "topper.headerTemplates": [
      {
        "defaultCStyled": {
          "headerBegin": "/**",
          "headerPrefix": "*",
          "headerEnd": "*/",
          "template": [
            "${headerBegin}",
            "${headerPrefix} ${fileName}, version ${fileVersion}",
            "${headerPrefix} @author ${author}",
            "${headerPrefix} @description ${description}",
            "${headerPrefix} @created ${createdDate}",
            "${headerPrefix} @copyright ${copyright}",
            **"${headerPrefix} @last-modified Tue Jan 16 2018 10:00:06 GMT-0500 (EST),**
            "${headerEnd}"
          ]
        }
      },```

when I edit the template .

**Comment by sidmishraw** [comment]
### RCA

The issue was caused because of a loose pattern match for finding the last-modified field.

### Fix

*  Added a strict pattern to match the last-modified field.

### Caveats

* The `FileSystemWatcher` API in the VS Code namespace is pretty limited at the moment. I plan to change the architecture in the upcoming releases in order to get a more robust templating engine in place.

**Comment by sidmishraw** [comment]
Also, if you have `autoSave` enabled, topper will keep updating the file since VS Code keeps on firing changed events.

The only workaround is to un-focus the file or close the tab.
> Note: The normal save should work fine though. The change event is fired once the file changes. So, the file is considered modified only after VS Code thinks it has changed.

Thanks for pointing out these bugs :)

Could you close the issue once you have verified the fix on your end. I'd like to know if it works fine for other settings.

**Comment by Louis-udm** [comment]
It is ok now for  modify the template. but for the first problem, you can refer to an other plugin "vscode-fileheader", it modify the "last-modified" before save the file when cmd+s.

I will be very willing to help you close this issue. :)

**Comment by sidmishraw** [comment]
In the `vscode-fileheader` extension, the developer uses the `vscode.workspace.onDidSaveTextDocument` event. Then inside the event, the dev calls the `document.save()`. This will cause an infinite loop since the `save()` will fire another onDidSaveTextDocument event.

There should be a way to unbind the listener after one change and then rebind  it at a later time inorder to prevent the infinite fire loop.

**Comment by sidmishraw** [comment]
I have decided to move forward with the `TextDocumentWillSaveEvent`. This event is a bit controversial since it is a pre-save event. Also, according to VS Code's API docs, the VS Code engine can ignore notifying the listeners of this event if they take more time  or fail to respond 3 times(?).

But, this event works and provides the desired effects.

**Comment by sidmishraw** [comment]
v0.3.2 out :)

**Comment by Louis-udm** [comment]
I tried a moment ago, it works very well! it sounds that TextDocumentWillSaveEvent is ok!
Good job, Thanks!

**Comment by sidmishraw** [comment]
😊
